version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "${GATEWAY_PORT}:3000"
    environment:
      - VOTING_SERVICE_URL=http://votingService:${VOTING_SERVICE_PORT}
      - FORUM_SERVICE_URL=http://forumService:${FORUM_SERVICE_PORT}

  voting_service:
    build: ./votingService
    ports:
      - "${VOTING_SERVICE_PORT}:5000"
    environment:
      - POSTGRES_HOST=${VOTING_DB_HOST}
      - POSTGRES_PORT=${VOTING_DB_PORT}
      - POSTGRES_DB=${VOTING_DB_NAME}
      - POSTGRES_USER=${VOTING_DB_USER}
      - POSTGRES_PASSWORD=${VOTING_DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  FORUM_service:
    build: ./forumService
    ports:
      - "${FORUM_SERVICE_PORT}:5001"
    environment:
      - MONGODB_HOST=${FORUM_DB_HOST}
      - MONGODB_PORT=${FORUM_DB_PORT}
      - MONGODB_DB=${FORUM_DB_NAME}
